# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
## Functional API
# 1번 세션 클리어
keras.backend.clear_session()

# 2번 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='linear')(il)

# 3번 모델의 시작과 끝 지정!
model = keras.models.Model(il, ol)

# 4번 컴파일
model.compile(loss='mse', optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 816ms/step - loss: 678.2750
Epoch 2/10
1/1 [==============================] - 0s 17ms/step - loss: 677.6524
Epoch 3/10
1/1 [==============================] - 0s 17ms/step - loss: 677.0301
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 676.4081
Epoch 5/10
1/1 [==============================] - 0s 16ms/step - loss: 675.7865
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 675.1652
Epoch 7/10
1/1 [==============================] - 0s 16ms/step - loss: 674.5441
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 673.9233
Epoch 9/10
1/1 [==============================] - 0s 13ms/step - loss: 673.3029
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 672.6828


In [7]:
y_pred = model.predict(x)
y_pred[:5]

1/1 [==============================] - 0s 37ms/step


array([[ 0.00999838],
       [-0.3999851 ],
       [-0.8099686 ],
       [-1.219952  ],
       [-1.6299355 ]], dtype=float32)

In [8]:
y[:5]

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [16]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = numpy.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

In [17]:
## Functional API
# 1번 세션 클리어
keras.backend.clear_session()
# 2번 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)
# 3번 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4번 컴파일
model.compile(loss='mse', optimizer='adam')

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 514ms/step - loss: 129.8982
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 129.6255
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 129.3531
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 129.0810
Epoch 5/10
1/1 [==============================] - 0s 15ms/step - loss: 128.8092
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 128.5377
Epoch 7/10
1/1 [==============================] - 0s 15ms/step - loss: 128.2666
Epoch 8/10
1/1 [==============================] - 0s 16ms/step - loss: 127.9957
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 127.7252
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 127.4550


In [19]:
y_pred = model.predict(x)
y_pred[:5]

1/1 [==============================] - 0s 55ms/step


array([[-0.00999644],
       [ 1.0639944 ],
       [ 2.1379852 ],
       [ 3.211976  ],
       [ 4.285967  ]], dtype=float32)

In [20]:
y[:5]

array([0, 0, 0, 0, 0])

## Quick Logistic Regression!

In [9]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

In [10]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [12]:
## Functional API
# 1번 세션 클리어
keras.backend.clear_session()

# 2번 레이어를 사슬처럼 엮기!
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 3번 모델의 시작과 끝 레이어 지정!
model = keras.models.Model(il, ol)

# 4번 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [13]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 705ms/step - loss: 6.5715 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 6.5639 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 6.5562 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 6.5486 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 6.5409 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 6.5333 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 6.5256 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 6.5180 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 6.5103 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 14ms/step - loss: 6.5027 - accuracy: 0.4500


In [14]:
y_pred = model.predict(x)
y_pred[:5]

1/1 [==============================] - 0s 58ms/step


array([[0.5024998 ],
       [0.2937065 ],
       [0.14617783],
       [0.06584442],
       [0.02820083]], dtype=float32)

In [15]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [21]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [22]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [23]:
x.shape, y.shape

((40,), (40,))

In [24]:
## Functional API

# 1 세션 클리어
keras.backend.clear_session()
# 2 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)
# 3 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)
# 4 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 1s 16ms/step - loss: 2.6197 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 9ms/step - loss: 2.6100 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5998 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5899 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 7ms/step - loss: 2.5805 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5707 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 7ms/step - loss: 2.5601 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5500 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5407 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 8ms/step - loss: 2.5304 - accuracy: 0.5250


In [26]:
y_pred = model.predict(x)
y_pred[:5]

2/2 [==============================] - 0s 7ms/step


array([[0.4951307 ],
       [0.62316257],
       [0.73603576],
       [0.82461554],
       [0.8879936 ]], dtype=float32)

In [27]:
y[:5]

array([0, 0, 0, 0, 0])