# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [1]:
from sklearn.datasets import fetch_california_housing

In [7]:
california = fetch_california_housing()

In [8]:
type(california)

sklearn.utils.Bunch

In [3]:
x = california.data
y = california.target

In [9]:
type(x), type(y)

(numpy.ndarray, numpy.ndarray)

In [10]:
import pandas as pd

In [12]:
pd.DataFrame(x, columns=california.feature_names).head(2)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127    1.02381       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137    0.97188      2401.0  2.109842     37.86   

   Longitude  
0    -122.23  
1    -122.22

In [13]:
pd.DataFrame(y, columns=california.target_names).head(2)

MedHouseVal
0        4.526
1        3.585

In [4]:
x.shape, y.shape

((20640, 8), (20640,))

In [14]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

In [15]:
########
# 모델링 : Sequential API
########
# 세션 클리어
keras.backend.clear_session()

# 모델 블록 발판 생성
model = keras.models.Sequential()

# 모델 블록 조립
model.add( keras.layers.Input(shape=(8,)) )
model.add( keras.layers.Dense(1) )

# 컴파일
model.compile(loss='mse', optimizer='adam')

# 양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [16]:
###########
# 모델 학습
###########
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
645/645 [==============================] - 2s 2ms/step - loss: 644924.1875
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 53522.2773
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 10775.7432
Epoch 4/10
645/645 [==============================] - 1s 2ms/step - loss: 6695.5317
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 3761.8608
Epoch 6/10
645/645 [==============================] - 1s 1ms/step - loss: 1725.9456
Epoch 7/10
645/645 [==============================] - 1s 1ms/step - loss: 623.2532
Epoch 8/10
645/645 [==============================] - 1s 1ms/step - loss: 186.5679
Epoch 9/10
645/645 [==============================] - 1s 1ms/step - loss: 71.3563
Epoch 10/10
645/645 [==============================] - 1s 1ms/step - loss: 50.3666


In [17]:
###########
# 모델 예측
###########
y_pred = model.predict(x)

645/645 [==============================] - 1s 1ms/step


In [18]:
y_pred[:5]

array([[ 3.5423102 ],
       [ 3.975024  ],
       [ 1.3848437 ],
       [ 0.14663424],
       [-0.762298  ]], dtype=float32)

In [19]:
y[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [20]:
x.shape, y.shape

((20640, 8), (20640,))

In [21]:
########
# 모델링 : Sequential API
########
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add( keras.layers.Input(shape=(8,)) )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(1) )

# 4. 컴파일
model.compile(loss='mse', optimizer='adam')

# 양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,377
Trainable params: 1,377
Non-trainable params: 0
_________________________________________________________________


In [22]:
###########
# 모델 학습
###########

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
645/645 [==============================] - 2s 2ms/step - loss: 1740.7827
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 3.2085
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 2.4279
Epoch 4/10
645/645 [==============================] - 2s 2ms/step - loss: 1.2251
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 0.7888
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 1.0098
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 1.0065
Epoch 8/10
645/645 [==============================] - 2s 3ms/step - loss: 0.8991
Epoch 9/10
645/645 [==============================] - 1s 2ms/step - loss: 2.2415
Epoch 10/10
645/645 [==============================] - 1s 2ms/step - loss: 24.6063


In [23]:
###########
# 모델 예측
###########

y_pred = model.predict(x)

645/645 [==============================] - 1s 2ms/step


In [24]:
y_pred[:5]

array([[3.9956815],
       [1.0589405],
       [3.49036  ],
       [3.3906019],
       [2.7147481]], dtype=float32)

In [25]:
y[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])