<a href="https://colab.research.google.com/github/OhYesLee/KT_python_jupyter_notebook/blob/main/1_1_Quick_Keras_Sequential.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
print('test')

test


In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 686ms/step - loss: 1410.8970
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 1409.9987
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1409.1005
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 1408.2029
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 1407.3054
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 1406.4083
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1405.5116
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 1404.6151
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 1403.7190
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 1402.8234


In [ ]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 112ms/step


array([ 9.9989288e-03, -1.4365830e+00, -2.8831649e+00, -4.3297472e+00,
       -5.7763290e+00, -7.2229109e+00, -8.6694927e+00, -1.0116075e+01,
       -1.1562656e+01, -1.3009238e+01, -1.4455820e+01, -1.5902402e+01,
       -1.7348986e+01, -1.8795567e+01, -2.0242149e+01, -2.1688730e+01,
       -2.3135313e+01, -2.4581896e+01, -2.6028477e+01, -2.7475060e+01],
      dtype=float32)

## Now, Your turn!

In [ ]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
x.shape,y.shape

((20,), (20,))

In [ ]:
## Sequential API
# 1번 청소 세션 클리어 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()
# 2번 모델 선언, 모델 발판 생성
model = keras.models.Sequential()
# 3번 모델 블록 조립, 모델 레이어 쌓기
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1))
# 4번 컴파일 
model.compile(loss='mse', optimizer = 'adam')

In [ ]:
model.fit(x, y, epochs = 10, verbose= 1)

Epoch 1/10
1/1 [==============================] - 0s 461ms/step - loss: 280.5103
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 280.1346
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 279.7593
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 279.3843
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 279.0095
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 278.6351
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 278.2610
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 277.8872
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 277.5137
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 277.1406


In [ ]:
print(y)

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x))

## Now, Your turn!

In [ ]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)