# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [3]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [4]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [5]:
x.shape, y.shape

((20,), (20,))

In [7]:
## Sequential API
# 1. 세션 클리어 : 이전에 사용했던 모델이 있다면 없애줘!
keras.backend.clear_session()

# 2. 모델 발판 생성
model = keras.models.Sequential()

# 3. 모델 레이어 쌓기
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

# 4. 컴파일
model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
y_pred = model.predict(x)

In [ ]:
y_pred.reshape(-1)

In [ ]:
y

## Now, Your turn!

In [ ]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [14]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [15]:
x.shape, y.shape

((20,), (20,))

In [16]:
## 모델링 : Sequential API
# 세션 클리어 : 기존의 모델이 메모리에 남아있다면 지워줘!
keras.backend.clear_session()

# 모델을 쌓을 발판 생성
model = keras.models.Sequential()

# 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

# 컴파일
model.compile(loss='mse', optimizer='adam')

In [17]:
model.fit(x, y, epochs=10, verbose=2)

Epoch 1/10
1/1 - 0s - loss: 180.6413 - 443ms/epoch - 443ms/step
Epoch 2/10
1/1 - 0s - loss: 180.3500 - 9ms/epoch - 9ms/step
Epoch 3/10
1/1 - 0s - loss: 180.0591 - 8ms/epoch - 8ms/step
Epoch 4/10
1/1 - 0s - loss: 179.7684 - 8ms/epoch - 8ms/step
Epoch 5/10
1/1 - 0s - loss: 179.4781 - 8ms/epoch - 8ms/step
Epoch 6/10
1/1 - 0s - loss: 179.1881 - 7ms/epoch - 7ms/step
Epoch 7/10
1/1 - 0s - loss: 178.8984 - 7ms/epoch - 7ms/step
Epoch 8/10
1/1 - 0s - loss: 178.6090 - 11ms/epoch - 11ms/step
Epoch 9/10
1/1 - 0s - loss: 178.3199 - 13ms/epoch - 13ms/step
Epoch 10/10
1/1 - 0s - loss: 178.0312 - 6ms/epoch - 6ms/step


In [18]:
y_pred = model.predict(x)

1/1 [==============================] - 0s 57ms/step


In [19]:
y_pred[:5]

array([[-0.0099956],
       [-1.1351086],
       [-2.2602217],
       [-3.3853347],
       [-4.5104475]], dtype=float32)

In [20]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [21]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

In [22]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [23]:
x.shape, y.shape

((20,), (20,))

In [26]:
## 모델링 : Sequential API
# 1. 세션 클리어 : 기존의 모델이 남아있다면 지워줘.
keras.backend.clear_session()

# 2. 레이어 발판 생성
model = keras.models.Sequential()

# 3. 레이어 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

# 4. 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [27]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 559ms/step - loss: 2.3846 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 2.3820 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 2.3793 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 2.3766 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 2.3740 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 2.3713 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 2.3686 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 17ms/step - loss: 2.3660 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 17ms/step - loss: 2.3633 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 2.3606 - accuracy: 0.5500


In [28]:
# 예측값
y_pred = model.predict(x)

1/1 [==============================] - 0s 72ms/step


In [29]:
y_pred[:5]

array([[0.49750018],
       [0.7337023 ],
       [0.884625  ],
       [0.95523214],
       [0.98343813]], dtype=float32)

In [30]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [31]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [32]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [33]:
x.shape, y.shape

((40,), (40,))

In [38]:
## 모델링 : Sequential API
# 1번. 청소
keras.backend.clear_session()

# 2번. 모델 발판 생성
model = keras.models.Sequential()

# 3번. .add()
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

# 4번. .compile()
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [39]:
# 학습
model.fit(x, y, verbose=1, epochs=10)

Epoch 1/10
2/2 [==============================] - 0s 12ms/step - loss: 15.7035 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 7ms/step - loss: 15.6730 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 9ms/step - loss: 15.6433 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 7ms/step - loss: 15.6129 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 7ms/step - loss: 15.5831 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 7ms/step - loss: 15.5529 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 7ms/step - loss: 15.5233 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 15.4940 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 9ms/step - loss: 15.4643 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 8ms/step - loss: 15.4340 - accuracy: 0.4750


In [40]:
y_pred = model.predict(x)

2/2 [==============================] - 0s 6ms/step


In [41]:
y_pred[:5]

array([[0.5048865 ],
       [0.26431316],
       [0.11235716],
       [0.04269242],
       [0.01546912]], dtype=float32)

In [42]:
y[:5]

array([0, 0, 0, 0, 0])