# Keras로 Linear&Logistic Regression 조금 더 맛보기
---

In [12]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

##Linear Regression on 쬐금 더 어려운 데이터

In [13]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

In [15]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [17]:
## 모델링 : Sequential API
# 1번. 세션 클리어 : 이전 모델이 남아있다면 날려줘!
keras.backend.clear_session()

# 2번. 모델 발판 생성 : 순차적으로 쌓을 발판!
model = keras.models.Sequential()

# 3번. 모델 블록 조립 : .add()
model.add( keras.layers.Input(shape=(13,)) )
model.add( keras.layers.Dense(1, activation='linear') )

# 4번. 컴파일
model.compile(loss='mse', optimizer='adam')

In [18]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 10491.3818
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 9687.6299
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 9033.5713
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 8538.5977
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 8071.3965
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 7625.3564
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 7221.2065
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 6806.4785
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 6423.8579
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 6051.6245


In [19]:
# 예측값 생성
y_pred = model.predict(x)

16/16 [==============================] - 0s 3ms/step


In [21]:
y_pred[:10].reshape(-1)

array([ 90.164055, 118.82594 , 116.53692 , 121.08837 , 122.228546,
       122.08316 ,  82.72904 ,  84.542564,  73.512634,  78.66877 ],
      dtype=float32)

In [22]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

---

In [23]:
boston = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv')

In [24]:
boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

In [27]:
x = boston.iloc[ : , :-1]
y = boston.iloc[ : , -1 ]

In [28]:
x.shape, y.shape

((506, 12), (506,))

In [31]:
## 모델링 2 : Sequential API
# 세션 클리어
keras.backend.clear_session()

# 시퀀셜하게 쌓을거야!
model = keras.models.Sequential()

# 레이어 조립
model.add( keras.layers.Input(shape=(12,)) )
model.add( keras.layers.Dense(1, activation='linear') )

# 컴파일
model.compile(loss=keras.losses.mean_squared_error, optimizer=keras.optimizers.Adam() )

In [32]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 43028.4180
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 39393.6758
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 35939.1055
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 32703.5156
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 29777.9199
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 27006.7734
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 24476.5938
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 22128.9590
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 20025.3027
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 18022.5371


In [33]:
# 예측
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

16/16 [==============================] - 0s 3ms/step


array([80.03402 , 51.468918, 67.12647 , 69.02092 , 61.39725 ],
      dtype=float32)

In [34]:
y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

## Logistic Regression 쬐금 더 어려운 데이터

In [35]:
from sklearn.datasets import load_breast_cancer

In [36]:
cancer = load_breast_cancer()

In [37]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것

In [38]:
x.shape, y.shape

((569, 30), (569,))

In [39]:
## 모델링 : Sequential API
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 발판 생성
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape=(30,)) )
model.add(keras.layers.Dense(1, activation='sigmoid') )

# 4. 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [40]:
## 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 31.3857 - accuracy: 0.6503
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 16.0854 - accuracy: 0.6977
Epoch 3/10
18/18 [==============================] - 0s 3ms/step - loss: 6.1126 - accuracy: 0.8049
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 2.3643 - accuracy: 0.8682
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 1.6177 - accuracy: 0.8629
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 1.5616 - accuracy: 0.8436
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 1.5490 - accuracy: 0.8418
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 1.5352 - accuracy: 0.8506
Epoch 9/10
18/18 [==============================] - 0s 3ms/step - loss: 1.5215 - accuracy: 0.8489
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 1.5058 - accuracy: 0.8471


In [41]:
## 예측값 생성
y_pred = model.predict(x)

18/18 [==============================] - 0s 2ms/step


In [42]:
y_pred[:5]

array([[0.0000000e+00],
       [0.0000000e+00],
       [7.4456137e-31],
       [5.6139426e-09],
       [3.6686622e-03]], dtype=float32)

In [43]:
y[:5]

array([0, 0, 0, 0, 0])