# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [24]:
from sklearn.datasets import load_iris

In [25]:
iris = load_iris()

In [26]:
x = iris.data
y = iris.target

In [27]:
x.shape, y.shape

((150, 4), (150,))

In [28]:
######################
# train set / test set 분리
# 조건 1. test set size = 10%
# 조건 2. 난수 고정 = 2023
######################
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test =\
    train_test_split(x, y, test_size=0.1, random_state=2023)

In [30]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((135, 4), (135,), (15, 4), (15,))

In [31]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [32]:
#######################
# 어떤 전처리 작업 필요 : One-Hot encoding
# Hint : y.shape
#######################
from tensorflow.keras.utils import to_categorical

In [33]:
class_n = len(np.unique(y_train))

In [34]:
## One-Hot Encoding

_train = to_categorical(y_train, class_n)
y_test = to_categorical(y_test, class_n)

In [35]:
y_train.shape

(135, 3)

In [36]:
########
# 모델링
########
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 레이어 조립
model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(3, activation='softmax') )

# 4. 컴파일
model.compile(loss=keras.losses.categorical_crossentropy,
              metrics=['accuracy'],
              optimizer='adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [37]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 2.3181 - accuracy: 0.6000
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 2.2722 - accuracy: 0.6074
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 2.2271 - accuracy: 0.6222
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 2.1873 - accuracy: 0.6222
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.1435 - accuracy: 0.6444
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 2.1034 - accuracy: 0.6593
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.0626 - accuracy: 0.6667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 2.0220 - accuracy: 0.6741
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 1.9835 - accuracy: 0.6741
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 1.9425 - accuracy: 0.6815


In [38]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 36ms/step


In [39]:
y_pred[:10]

array([[0.29005203, 0.00180257, 0.70814544],
       [0.5582749 , 0.00521021, 0.43651488],
       [0.44363594, 0.00732673, 0.5490374 ],
       [0.4168094 , 0.00111736, 0.5820732 ],
       [0.5894442 , 0.00329954, 0.4072563 ],
       [0.29022262, 0.0031566 , 0.70662075],
       [0.26345956, 0.00561007, 0.73093027],
       [0.40880945, 0.00697068, 0.5842198 ],
       [0.6124172 , 0.05683593, 0.33074692],
       [0.69455904, 0.00665539, 0.29878563]], dtype=float32)

In [40]:
y_test[:10]

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [41]:
x_train.shape, y_train.shape

((135, 4), (135, 3))

In [42]:
########
# 모델링 : Sequential API
########
# 1. 세션 클리어 : 기존의 모델 구조가 남아있다면 날려줘
keras.backend.clear_session()
# 2. 모델 선언 : 레이어 블록을 쌓을 발판 생성
model = keras.models.Sequential()
# 3. 레이어 블록 조립 : .add()
model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(3, activation='softmax') )
# 4. 컴파일
model.compile(loss=keras.losses.categorical_crossentropy,
            #   loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])
# 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [43]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 1s 3ms/step - loss: 1.1447 - accuracy: 0.3037
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0480 - accuracy: 0.3407
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9920 - accuracy: 0.4000
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9556 - accuracy: 0.6296
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9249 - accuracy: 0.7037
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8992 - accuracy: 0.6815
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8719 - accuracy: 0.6889
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8467 - accuracy: 0.7333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8249 - accuracy: 0.7037
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8046 - accuracy: 0.6889


In [44]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 50ms/step


In [45]:
y_pred[:10]

array([[0.13651447, 0.23158506, 0.63190037],
       [0.2672152 , 0.3478949 , 0.38488984],
       [0.25097322, 0.32494408, 0.42408267],
       [0.14089674, 0.27394426, 0.58515906],
       [0.23627505, 0.34530723, 0.41841757],
       [0.14952636, 0.23470715, 0.6157665 ],
       [0.20016864, 0.2814907 , 0.5183407 ],
       [0.24443527, 0.32063824, 0.43492636],
       [0.48297977, 0.33820832, 0.17881192],
       [0.27352497, 0.37531054, 0.35116443]], dtype=float32)

In [46]:
y_test[:10]

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)