In [2]:
import tensorflow as tf
from tensorflow import keras

In [4]:
## Functional API

# 1번 세션 클리어
keras.backend.clear_session()

# 2번 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(5,5,3))
cl = keras.layers.Conv2D(filters=1,             # 제작하려는 feature map의 수
                         kernel_size=(3,3),     # filter의 가로세로 사이즈
                         strides=(1,1),         # filter가 어떻게 훑을 것인지 값 지정
                         activation='relu')(il)

pl = keras.layers.MaxPool2D(pool_size=(2,2), strides=(1,1),)(cl)

# 3번 모델의 시작과 끝 지정
model = keras.models.Model(il, pl)

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 conv2d (Conv2D)             (None, 3, 3, 1)           28        
                                                                 
 max_pooling2d (MaxPooling2D  (None, 2, 2, 1)          0         
 )                                                               
                                                                 
Total params: 28
Trainable params: 28
Non-trainable params: 0
_________________________________________________________________


In [ ]:
((3*3*3)+1) * 1

28

In [6]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])
x = tf.reshape(x, [1, 3, 3, 1])
x.shape

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[5.],
         [6.]],

        [[8.],
         [9.]]]], dtype=float32)>

In [7]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
                                           strides=(2, 2),
                                           padding='same')
max_pool_2d(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[5.],
         [6.]],

        [[8.],
         [9.]]]], dtype=float32)>